---
name: test
on:
  pull_request:
  workflow_dispatch:
  workflow_call:
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    uses: delineaxpm/github-workflows/.github/workflows/test.yml@main
    secrets: inherit
